# -*- coding: utf-8 -*-
"""mirnet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kdQejPBFpQ55qMmnuwDQO2k2kEFfHUVo
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/soumik12345/MIRNet
# %cd MIRNet

import cv2
#edit
image=cv2.imread("NORMAL (254).png",0)
image = cv2.cvtColor(image, cv2.COLOR_GRAY2BGR)
cv2.imwrite("mir5.png",image)

!pip install -q wandb

from glob import glob
from PIL import Image
from matplotlib import pyplot as plt
from mirnet.inference import Inferer
from mirnet.utils import download_dataset, plot_result

import tensorflow as tf
import numpy as np
print(tf.__version__)

inferer = Inferer()
inferer.download_weights('1sUlRD5MTRKKGxtqyYDpTv7T3jOW6aVAL')
inferer.build_model(
    num_rrg=3, num_mrb=2, channels=64,
    weights_path='low_light_weights_best.h5'
)
inferer.model.summary()

inferer.model.save('mirnet')

IMAGE_LOC = '/content/mir2.png'

original_image, output_image = inferer.infer(IMAGE_LOC)
plot_result(original_image, output_image)
plt.imshow(output_image)
plt.show()

